apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: simple-remote-partitioned-job
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: simple-remote-partitioned-job
          name: simple-remote-partitioned-job
          resources: {}
          imagePullPolicy: IfNotPresent
          env:
          - name: meta__jdbc__url
            value: 'jdbc:mysql://mysql.default.svc.cluster.local:3306/simple_partitioned_job?allowPublicKeyRetrieval=true&useSSL=false'
          - name: meta__jdbc__user
            value: 'root'
          - name: meta__jdbc__password
            value: 'password'
          - name: worker__image
            value: 'file:simple-remote-partitioned-job'          
          - name: worker__gridsize
            value: '2'          
          - name: job__name
            value: 'simpleRemoteJob-20'          
          - name: simulate__error__for__steps
            value: '999'                
      restartPolicy: Never
      
status: {}

